version: '3'

tasks:
  setup-tools:
    desc: Install required tools (buf, protoc-gen-go, etc.)
    cmds:
      - |
        if ! command -v buf &> /dev/null; then
          go install github.com/bufbuild/buf/cmd/buf@latest
        fi
      - |
        if ! command -v protoc-gen-go &> /dev/null; then
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        fi
      - |
        if ! command -v protoc-gen-go-grpc &> /dev/null; then
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        fi

  generate:
    desc: Generate protobuf files
    deps: [setup-tools]
    cmds:
      - buf generate

  lint:
    desc: Lint protobuf files
    deps: [setup-tools]
    cmds:
      - buf lint

  breaking:
    desc: Check for breaking changes
    deps: [setup-tools]
    cmds:
      - buf breaking --against '.git#branch=main'

  format:
    desc: Format protobuf files
    deps: [setup-tools]
    cmds:
      - buf format -w

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf gen/

  commit:
    desc: Commit changes using conventional commits
    cmds:
      - npx git-cz

  evans:
    desc: Start Evans gRPC client
    cmds:
      - evans --proto ./string_phone/**/*.proto --port 8080

  test:
    desc: Run all checks
    deps: [lint, breaking]
    cmds:
      - echo "All checks passed!"